fix unused-but-set-variable and unused-variable compilation errors
Fixes the following errors:

unused-but-set-variable errors:
-------------------------------

pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘virtual void pxUtilTest::TearDown()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:102:12: error: variable ‘sysRet’ set but not used [-Werror=unused-but-set-variable]
       bool sysRet;
            ^~~~~~
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadImage3ArgsPngSuccessTest()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:114:15: warning: unused variable ‘loadImageSuccess’ [-Wunused-variable]
       rtError loadImageSuccess = rtLoadFile("supportfiles/status_bg.png", d);
               ^~~~~~~~~~~~~~~~
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadPNGImage3ArgsCreateReadStructFailTest()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:231:15: warning: unused variable ‘loadImageSuccess’ [-Wunused-variable]
       rtError loadImageSuccess = rtLoadFile("supportfiles/status_bg.png", d);
               ^~~~~~~~~~~~~~~~
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadAPngSuccessTest()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:275:17: warning: unused variable ‘loadImageSuccess’ [-Wunused-variable]
         rtError loadImageSuccess = rtLoadFile("supportfiles/apngimage.png", d);
                 ^~~~~~~~~~~~~~~~

pxCore/tests/pxScene2d/test_rtZip.cpp: In member function ‘void rtZipTest::isZipTest()’:
pxCore/tests/pxScene2d/test_rtZip.cpp:111:15: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]
       rtError ret = rtLoadFile("supportfiles/test.html", buffer);
               ^~~

pxCore/tests/pxScene2d/pxscene2dtestsmain.cpp:50:7: error: variable ‘urlIndex’ set but not used [-Werror=unused-but-set-variable]
   int urlIndex  = -1;
       ^~~~~~~~

unused-variable errors:
-----------------------

pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadImage3ArgsPngSuccessTest()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:116:15: warning: unused variable ‘loadImageSuccess’ [-Wunused-variable]
       rtError loadImageSuccess = rtLoadFile("supportfiles/status_bg.png", d);
               ^~~~~~~~~~~~~~~~
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadPNGImage3ArgsCreateReadStructFailTest()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:233:15: warning: unused variable ‘loadImageSuccess’ [-Wunused-variable]
       rtError loadImageSuccess = rtLoadFile("supportfiles/status_bg.png", d);
               ^~~~~~~~~~~~~~~~
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadAPngSuccessTest()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:277:17: warning: unused variable ‘loadImageSuccess’ [-Wunused-variable]
         rtError loadImageSuccess = rtLoadFile("supportfiles/apngimage.png", d);
                 ^~~~~~~~~~~~~~~~