add missing 'uv' library
Fixes the follwoing linking failure:
  /usr/bin/ld: ../../../build/glut/libpxCore.a(rtNode.cpp.o): undefined reference to symbol 'uv_default_loop'
  //usr/lib64/libuv.so.1: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status