fix -Werror=unused-but-set-variable compilation error
Fixes the following compilation error:
pxCore/src/rtPathUtils.cpp: In function ‘rtError rtGetHomeDirectory(rtString&)’:
pxCore/src/rtPathUtils.cpp:59:11: error: variable ‘e’ set but not used [-Werror=unused-but-set-variable]
   rtError e = RT_FAIL;
           ^